VK:
  APP_ID: 51765688
  ACCESS_TOKEN: vk1.a.BOXp-WXAZ4AhYdY1t6dgxDW7jY-Wxhak3lLxi2K2insYQylQJjtas9jgQ7MY9yP19114KJLYdT9ITfjZQgWtOkePsttrVtM1nZnsvY70KrwVBLwy-nA0MraNlInfRKPplSYHKVPfgrPopbZwfY_3uPlZEmDDPPV3bHkqPy5bM67bUfAeqjfxmat_OTERFKSg7u7-by2lnPXhKaE7wxJ9Jg

YADISK:
  ACCESS_TOKEN: y0_AgAAAAAHVqq6AADLWwAAAADulcwQxjwKBW8sTiez6i-LQSzGeUSpQrI